module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts
params:
  authors:
    thumbnail:
      desktop: "100x100"
      mobile: "100x100"
    image:
      desktop: "100x100"
      mobile: "100x100"
    post:
      desktop: "50x50"
      mobile: "50x50"
  posts:
    thumbnail:
      desktop: "414x177"
      mobile: "300x129"
      scrollsnap: "240x103"
    image:
      desktop: "856x"
      mobile: "300x"